### PR TITLE
Add support to fixed times drag and drop and support IE

### LINKED ISSUE #2327: Drag and Drop Timeline for external events drop without mouseposition
Hey,

I have lot of external items that I want to drag and drop into the group timeline.
I want to drop an item with fix time, start and end. 

like:

 ```
var item = {
      id: new Date(),
      type: itemType,
      content: event.target.innerHTML.trim(),
      start: new Date(2016,11,17,12,0,0,0),
      end: new Date(2016,11,17,22,0,0,0)
    };
```

But if I drop the item into the timeline they always takes the position of the mouse pointer for the start time. 

How can I solve this problem?

### PR DESCRIPTION
**Pull request by yotamberk**
fixed #2327 and #2370

### CODE REVIEW

**Comment by gulench** [comment]
A couple of more issues (there could be more!) from a cross-browser support perspective:

1. IE does not like "text/plain" for the `dataTransfer.setData` and `dataTransfer.getData` calls; instead, "text" works.

```js
  event.dataTransfer.setData("text/plain", JSON.stringify(item));
  var itemData = JSON.parse(event.dataTransfer.getData("text/plain"))
```

2. `ItemSet.prototype.groupFromTarget` fails to detect the group where the item is dropped, due to the way the dropped position is detected (usage of `event.x` and `event.y`). Would `event.clientX` and `event.clientY` be more appropriate?

**Comment by yotamberk** [comment]
Thanks @gulench! You are right! I'll add this too the PR

**Comment by yotamberk** [comment]
@gulench I'm not sure what you mean in the first problem. It is already in text form. What do you think should be the fix?

**Comment by Clarence344** [comment]
Hey everybody,

I dont understand the changes. 
If I include   <link href="../../../dist/vis-timeline-graph2d.min.css" rel="stylesheet" type="text/css" />
The new function does not work.

And If I change or fix the start and end date the item drop anywhere of mouseposition 

like
`
var isFixedTimes = (event.target.innerHTML.split('-')[2] && event.target.innerHTML.split('-')[2].trim() == 'fixed times')
    if (isFixedTimes) {
      item.start = new Date();
      item.end = new Date(1000*60*10 + (new Date()).valueOf());
    }
`

thanks

**Comment by yotamberk** [comment]
``` javascript
if (isFixedTimes) {
      item.start = new Date("2016-12-01T00:00:00.000Z"'); //
    item.end = new Date("2016-12-02T00:00:00.000Z");
  }
```
Try this and see where the item is placed.

**Comment by Clarence344** [comment]
@yotamberk 

I have no changes mhmm :(

there is the code:

...
`<link href="../../../dist/vis-timeline-graph2d.min.css" rel="stylesheet" type="text/css" />`


var isFixedTimes = (event.target.innerHTML.split('-')[2] && event.target.innerHTML.split('-')[2].trim() == 'fixed times')
    if (isFixedTimes) {
      item.start = new Date("2016-12-01T00:00:00.000Z"); 
    item.end = new Date("2016-12-02T00:00:00.000Z");
  }
    event.dataTransfer.setData("text", JSON.stringify(item));

thanks

**Comment by yotamberk** [comment]
@Clarence344 Let me check it out

**Comment by yotamberk** [comment]
@Clarence344 I don't know what's not working for you. It works fine for me. What browser are you using?

**Comment by Clarence344** [comment]
Hi,

I use safari and/or Google chrome Browser mhmm

**Comment by yotamberk** [comment]
@Clarence344  did you pull from this branch and build? 
@mojoaxel I think you can review and merge this PR. It's working for me. Try it out to see if it's working for you?

**Comment by Clarence344** [comment]
@yotamberk I dont know what you mean? Dynamik Code in github?

**Comment by yotamberk** [comment]
This feature will work only if you have this branch with the feature added here in this PR. Once this PR is accepted (if and when), the feature will be available in `almende/develop`. Until then, you can fork my branch `yotamberk:dnd-by-time` and check it out there, OR download this PR as a bundle, build it and try out the example supplied (and play around with it)

File: lib/timeline/Core.js [hunk 1]
```diff
@@ -248,16 +248,16 @@ Core.prototype._create = function (container) {
   function handleDrop(event) {
     // return when dropping non-vis items 
     try {
-      var itemData = JSON.parse(event.dataTransfer.getData("text/plain"))
```
Comment (mojoaxel) [inline lib/timeline/Core.js]: This line throws the error `Invalid argument` in IE10

Comment (mojoaxel) [inline lib/timeline/Core.js]: It looks like the whole drop event is different in IE10.

Comment (yotamberk) [inline lib/timeline/Core.js]: Yeah I see it now. I'm not sure if I should do this in 2 iterations. It might be worth accepting this PR and I'll submit another PR with IE10 support

Comment (mojoaxel) [inline lib/timeline/Core.js]: Ok, with me.
