### PR TITLE
fix #2613 with if statement, and null for pointer value rather than r…

### LINKED ISSUE #2613: Network - Navigation Zoom is broken (4.18)
After #2377 commit to 4.18 Zoom events for Navigation at Network module are broken. Example of it is active at official example page - http://visjs.org/examples/network/other/navigation.html

`Uncaught ReferenceError: pointer is not defined` - when trying to zoom in or zoom out with help of bottom buttons.

### PR DESCRIPTION
**Pull request by CapitanMorgan**
with if statement, and passing null for pointer value rather than referencing it when undefined

### CODE REVIEW

File: lib/network/modules/components/NavigationHandler.js [hunk 1]
```diff
@@ -160,7 +160,12 @@ class NavigationHandler {
 
     this.body.view.scale = scale;
     this.body.view.translation = { x: tx, y: ty };
-    this.body.emitter.emit('zoom', { direction: '+', scale: this.body.view.scale, pointer: pointer });
+    if (typeof(pointer) != 'undefined') {
```
Comment (Tooa) [inline lib/network/modules/components/NavigationHandler.js]: Why do we need this conditional expression here? There is no `pointer` in the scope, so this expression always evaluates to `false`, right?

File: lib/network/modules/components/NavigationHandler.js [hunk 2]
```diff
@@ -172,7 +177,11 @@ class NavigationHandler {
 
     this.body.view.scale = scale;
     this.body.view.translation = { x: tx, y: ty };
-    this.body.emitter.emit('zoom', { direction: '-', scale: this.body.view.scale, pointer: pointer });
+    if (typeof(pointer) != 'undefined') {
```
Comment (Tooa) [inline lib/network/modules/components/NavigationHandler.js]: Same as above.

**Comment by CapitanMorgan** [comment]
Ill remove the if, i just through it together hastily and thought the previous person who added this pointer reference, actually had a scenario were it might not be null. Ill just pass null, not sure what portion of doc needs updating.
