### PR TITLE
Group editable bug

### LINKED ISSUE #2367: Editing groups doesn't work
Trying to drag groups when `groupEditable: true` doesn't work.

Uncaught TypeError: this.groupsData.update is not a function(…)

occurs in the console log.

### PR DESCRIPTION
**Pull request by yotamberk**
fixes #2367, #2328

### CODE REVIEW

File: lib/timeline/component/ItemSet.js [hunk 1]
```diff
@@ -1601,25 +1605,23 @@ ItemSet.prototype._onGroupDrag = function (event) {
...
 			var targetGroup = groupsData.get(group.groupId);
 			var draggedGroup = groupsData.get(this.groupTouchParams.group.groupId);
 			
 			// switch groups
 			if (draggedGroup && targetGroup) {
 				this.options.groupOrderSwap(draggedGroup, targetGroup, this.groupsData);
-				this.groupsData.update(draggedGroup);
-				this.groupsData.update(targetGroup);
+  			groupsData.update(draggedGroup);
+        groupsData.update(targetGroup);
```
Comment (mojoaxel) [inline lib/timeline/component/ItemSet.js]: here is something wrong with the indent

Comment (mojoaxel) [inline lib/timeline/component/ItemSet.js]: here is something wrong with the indent

**Comment by yotamberk** [comment]
@mojoaxel fixed indentation
