### PR TITLE
Fix #2285

### LINKED ISSUE #2285: Timeline onUpdate no longer working in v4.17.0
I just upgraded to v4.17.0 and noticed `onUpdate` callback for the Timeline is not being triggered. Its not working in the example demo either: http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html

### PR DESCRIPTION
**Pull request by yotamberk**
closes #2285

### CODE REVIEW

File: lib/timeline/component/item/Item.js [hunk 1]
```diff
@@ -141,6 +141,42 @@ Item.prototype.repositionY = function() {
 };
 
 /**
+ * Repaint a drag area on the center of the item when the item is selected
```
Comment (mojoaxel) [inline lib/timeline/component/item/Item.js]: Why did you mode the function in the file? Its confusing... :-)
