### PR TITLE
Network: Fix handling of multi-fonts 

### LINKED ISSUE #3408: network - glyph - node font.multi fontAwesome icon blank
Hi,

I tried to specify a node from the multifont example with a FontAwesome glyph, but the icon I was trying to use showed up blank? 

```js
{ id: 3, font: { multi: 'html', face: 'FontAwesome' }, label: ' \uf286 <b>This</b> is an\n<i>html</i> <b><i>multi-</i>font</b> <code>label</code>', x: 40, y: 40 },
```

Is it expected or a bug? 

Or perhaps there is another way to combine an image with text in an node without SVG? kind regards!!!

### PR DESCRIPTION
**Pull request by wimrijnders**
Fixes #3408, #2677.

This PR serves to get the handling of the font options right. The fixing of the issue is more or less a side-effect. As a special note, with this PR the group options for fonts are finally handled correctly.

Guiding principles:
- Option values should *not* be changed inline. They should remain as entered.
- Priority order for options should be respected: `node, group, default node, global default`.

## Changes
- Got rid of `Label#parseOptions()`. This changes the option values, and we want to keep them as
  specified.
- Adjusted usage of groups, at least for the font options in groups.

  Group font options were merged into the options of a given node instance, and the label
  handling requires these to be separate. *In fact, it is questionable if the group options
  should be merged into the node instance options at all.*

- Unit tests for the setting of font options in all manners have been added.
- **Special Note:** The added unit tests picked up an unrelated bug in `util.deepExtend()` and `util.selectiveDeepExtend()`;  added an extra check on `null` there.

### Further changes

- Removed member `edgeOptions` in module `EdgesHandler`, it's just a reference to `this.options`
- Removed member `nodeOptions` in module `NodesHandler`, it was useless for the same reason
- Added/edited commenting extensively
- Completely rewrote `Label.propagateFonts()`, additional notes :
  - Special handling in the old code of multi-font `mono` has been dropped; if users want to
  have a non-proportional font for `mono`, that's their problem.
  - Special handling of `ratio` has been dropped. This does not have any effect on the outcome. The value of `ratio` was always `1` in all the cases I have conceived to test.

## Final Comment

If anything is to be concluded from this fix, it's that the option setup and handling within
`Network` is unnecessarily complicated. This urgently needs to be looked at.

In particular, the **prototype chaining of options appears to be deficient**. While the idea is 
elegant in itself, the prototype order is not sufficient to handle all option sequences; in fact,
the code is rife with exceptions on it. Prototype chaining needs to be replaced with something
probably less elegant but better suited to the task.

### CODE REVIEW

File: lib/network/modules/Groups.js [hunk 1]
```diff
@@ -75,14 +75,17 @@ class Groups {
...
-   * @return {Object} group      The created group, containing all group options
+   * Get group options of a groupname.
+   * If groupname is not found, a new group may be created.
+   *
+   * @param {*}       groupname     Can be a number, string, Date, etc.
+   * @param {boolean} [create=true] If true, create a new group
+   * @return {Object} The found or created group
    */
-  get(groupname) {
+  get(groupname, create = true) {
```
Comment (yotamberk) [inline lib/network/modules/Groups.js]: I personally like more declarative variables. I think it should be: `create` => `shouldCreate`

File: lib/network/modules/NodesHandler.js [hunk 2]
```diff
@@ -1,9 +1,8 @@
 let util = require("../../util");
 let DataSet = require('../../DataSet');
 let DataView = require('../../DataView');
-
 var Node = require("./components/Node").default;
-var Label = require("./components/shared/Label").default;
+
```
Comment (yotamberk) [inline lib/network/modules/NodesHandler.js]: extra line

File: lib/network/modules/components/shared/Label.js [hunk 3]
```diff
@@ -178,141 +202,178 @@ class Label {
...
 
+   /**
+    * Return all options values for the given multi-font.
+    *
+    * All available option objects are trawled in the set order to construct the option values.
+    *
+    * @param {MultiName} multiName sub path for the mod-font
+    * @returns {ModOptions}
+    */
+    var getFontOptions = (multiName) => {
```
Comment (yotamberk) [inline lib/network/modules/components/shared/Label.js]: Why do you use `var`?  Why not use `const` and `let`? 
(for consistency)

File: lib/network/modules/components/shared/Label.js [hunk 4]
```diff
@@ -584,7 +645,14 @@ class Label {
         }
       }
     }
-    ctx.font = (values.mod + " " + values.size + "px " + values.face).replace(/"/g, "");
+
+    var fontString = "";
+    if (values.mod !== undefined && values.mod !== "") {  // safeguard for undefined - this happened
+      fontString += values.mod = " ";
```
Comment (yotamberk) [inline lib/network/modules/components/shared/Label.js]: I think you mean `fontString += values.mod + " "` ? It seems really weird to me if you meant to assign `values.mod = " "` and simultaneously add a space to `fontString`

File: lib/network/modules/components/shared/Label.js (hunk 3 above)
Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: A quick response on this one in passing:

I prefer `var` because chrome has issues dealing with `const` and `let`, it can't seem to display the values correctly inline (usually shows `undefined` even though it has a value). I find this bothersome to the point of forsaking them, even though `let` would be better.

If you have a solution for this, let me know.

Comment (yotamberk) [reply lib/network/modules/components/shared/Label.js]: But it seems that you douse `let` in the rest of the file. How does that work?

Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: I really try to use `let`. But if it gets in the way of debugging, I revert it to `var`.

File: lib/network/modules/Groups.js (hunk 1 above)
Comment (wimrijnders) [reply lib/network/modules/Groups.js]: :+1:

File: lib/network/modules/NodesHandler.js (hunk 2 above)
Comment (wimrijnders) [reply lib/network/modules/NodesHandler.js]: You mean that there are two empty lines? I actually prefer this, for better visual separation. I do it between methods as well, and in other places where I think a bigger distinction between blocks is useful.

File: lib/network/modules/components/shared/Label.js (hunk 3 above)
Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: Oh well, I can change this since I'm done with debugging.

File: lib/network/modules/components/shared/Label.js (hunk 4 above)
Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: Indeed. Good catch.

File: lib/network/modules/components/shared/Label.js [hunk 5]
```diff
@@ -178,141 +202,178 @@ class Label {
...
-     * @return {*|null} value if found, null otherwise.
-     */
-    var getP = function(options, mod, property) {
-      let opt = pathP(options, mod);
+   /**
+    * Collect all own-property values from the font pile that aren't multi-font option objectss.
+    *
+    * @returns {object} object with all current own basic font properties
+    */
+    let getBasicOptions = () => {
```
Comment (mbroad) [inline lib/network/modules/components/shared/Label.js]: I'm seeing a lot of nested function calls and wondering if it is a micro optimization to bring them up a level, so that they're initialized with the class, rather than initialized with every call to the function that encapsulates them.

File: test/Label.test.js [hunk 6]
```diff
@@ -418,6 +435,686 @@ describe('Network Label', function() {
...
+          bold: {
+            color: 'black'
+          }
+        }
+      },
+    });
+
+    assert.equal(modBold(0).color, 'black');    // nodes default
+    assert.equal(modBold(1).color, 'black');    // more specific bold value overrides group value
+    assert.equal(modBold(2).color, 'black');    // idem
```
Comment (mbroad) [inline test/Label.test.js]: Idem?

Comment (mbroad) [reply test/Label.test.js]: Why are these three changed, and the others aren't? I'm missing something here...

File: test/Label.test.js [hunk 7]
```diff
@@ -418,6 +435,686 @@ describe('Network Label', function() {
...
+    assert.equal(modBold(1).color, 'black');    // more specific bold value overrides group value
+    assert.equal(modBold(2).color, 'brown');    // bold group value overrides bold node value
+    assert.equal(modBold(3).color, 'green');    // unchanged
+    assert.equal(modBold(4).color, 'orange');   // unchanged
+
+
+    //
+    // Same initialization as previous with a color set for the default node font
+    //
+    data.nodes = new vis.DataSet(dataNodes);  // Need to reset nodes, changed in previous
```
Comment (mbroad) [inline test/Label.test.js]: This isn't really a reset is it?

It's a new dataset, but the since dataNodes is a mutable array of mutable objects, and not a function who's return value is a new array of objects, the nodes have not been reset.

File: test/Label.test.js [hunk 8]
```diff
@@ -418,6 +435,686 @@ describe('Network Label', function() {
...
+    // console.log(fontOption(1));
+
+    assert.equal(modBold(1).color, '#343434');  // Reverts to default 
+    assert(!fontOption(1).multi);               // idem 
+    assert.equal(modBold(6).color, 'blue');     // unchanged
+    assert(fontOption(6).multi);                // unchanged
+
+    done();
+  });
+
```
Comment (mbroad) [inline test/Label.test.js]: Great addition of tests! Well done!

I would suggest, however, refactoring these very large tests into a number of much smaller tests, in separate test classes where required, and making use of `before` and `after` to set up the state you need.

**Comment by wimrijnders** [comment]
@mbroad review :+1, you're being sharp.

File: lib/network/modules/NodesHandler.js [hunk 9]
```diff
@@ -144,7 +142,9 @@ class NodesHandler {
       throw 'Internal error: mass in defaultOptions of NodesHandler may not be zero or negative';
     }
 
-    util.extend(this.options, this.defaultOptions);
+    //this.options = {};
+    //util.extend(this.options, this.defaultOptions);  // Candidate for the Hall of Shame!
```
[the remark this answers is not in the document]
Comment (wimrijnders) [reply lib/network/modules/NodesHandler.js]: Heh. For the epitaph, actually. Major stupidity was performed here. I do this often in my own code, so that I remember not to do that thing every time I encounter the comment.

But this is shared code, and keeping it in is just vanity. Hereby gone.

File: lib/network/modules/components/shared/Label.js [hunk 10]
```diff
@@ -2,11 +2,24 @@ let util = require('../../../../util');
 let ComponentUtil = require('./ComponentUtil').default;
 let LabelSplitter = require('./LabelSplitter').default;
 
+/**
+ * @typedef {'bold'|'ital'|'boldital'|'mono'|'normal'} MultiName
+ *
```
[the remark this answers is not in the document]
Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: Ok, although I do want to convey that this is the list of names of special fonts that can be used when multi-font is enabled.

Will you settle for `MultiFontStyle`?

File: lib/network/modules/components/shared/Label.js [hunk 11]
```diff
@@ -2,11 +2,24 @@ let util = require('../../../../util');
...
+ * The allowed specifiers of multi-fonts.
+ */
+
+/**
+ * @typedef {{color:string, size:number, face:string, mod:string, vadjust:number}} ModOptions
```
[the remark this answers is not in the document]
Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: :+1:

File: lib/network/modules/components/shared/Label.js [hunk 12]
```diff
@@ -16,59 +29,69 @@ class Label {
...
+   * Init the font Options structure.
    *
-   * @param {Object} parentOptions
-   * @param {Object} newOptions
-   * @param {boolean} [allowDeletion=false]
-   * @static
+   * Member fontOptions serves as an accumulator for the current font options.
+   * As such, it needs to be completely separated from the node options.
+   *
+   * @param {Object} options
```
[the remark this answers is not in the document]
Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: Other options, whatever the user specified or otherwise the defaults.

File: lib/network/modules/components/shared/Label.js [hunk 13]
```diff
@@ -16,59 +29,69 @@ class Label {
...
+   * @private
    */
-  static parseOptions(parentOptions, newOptions, allowDeletion = false) {
-    if (Label.parseFontString(parentOptions, newOptions.font)) {
-      parentOptions.vadjust = 0;
-    }
-    else if (typeof newOptions.font === 'object') {
-      util.fillIfDefined(parentOptions, newOptions.font, allowDeletion);
+  initFontOptions(options) {
```
[the remark this answers is not in the document]
Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: Well, sort of. The underscore prefix was already present when I first came here.
There's no written convention about it. I would personally like them to signify 'methods internal to the project', but I haven't even proposed this.

The docs are vague when it comes to programming conventions. This is actually something that needs to be addressed (although, now, for many things you can just say 'it needs to pass linting').

File: lib/network/modules/components/shared/Label.js [hunk 14]
```diff
@@ -16,59 +29,69 @@ class Label {
...
+    let newFont = options.font;  // Only this member used!
+
+    // Get the structure right
+    util.forEach(options.font, (prop, n) => {
+      if (typeof prop === 'object') {
```
[the remark this answers is not in the document]
Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: Er. Oops. Seldom does it occur that someone's paranoia overshadows mine.

I'm rewriting this to use the `MultiFontStyle` list as in the jsdoc typedef. We know exactly which multi-fonts should be there, might as well use this knowledge.

File: lib/network/modules/components/shared/Label.js [hunk 15]
```diff
@@ -178,141 +202,178 @@ class Label {
...
+   *   - search in option group 'bold' in local properties
+   *   - search in main font option group in local properties
+   *
+   * ---------------------------------------------------------------------
+   * @param {Array.<object>} pile  sequence of option objects to consider.
+   *                               First item in list assumed to be the newly set options.
    */
-  propagateFonts(options, groupOptions, defaultOptions) {
-    if (!this.fontOptions.multi) return;
+  propagateFonts(pile) {
```
[the remark this answers is not in the document]
Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: Every time the options or data change. In the regular flow, it shouldn't be called at all (which is something that I should actually confirm)

File: lib/network/modules/components/shared/Label.js [hunk 16]
```diff
@@ -178,141 +202,178 @@ class Label {
...
+    let fontPile = [];   // sequence of font objects to consider, order important
+    let mods = ['bold', 'ital', 'boldital', 'mono'];
```
[the remark this answers is not in the document]
Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: :+1:

File: lib/network/modules/components/shared/Label.js (hunk 5 above)
Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: OK. My long-term planning is to isolate this pile handling code in a separate class. This is the approach that I want to use to replace the prototype chaining in options. I thought it was too early to make a class of it now.

But fair enough, I can define them as private methods for the time being. Wrt. 'micro optimization', it's an easy task to raise them to class-level, and every teeny bit helps.

File: lib/network/modules/components/shared/Label.js [hunk 17]
```diff
@@ -178,141 +202,178 @@ class Label {
...
       }
 
+      return result;
+    }
+
+
+    //
+    // Main body of the method
+    //
+
```
[the remark this answers is not in the document]
Comment (wimrijnders) [reply lib/network/modules/components/shared/Label.js]: ok. The idea was to indicate where the actual function code began, after the definitions of the local function. But I just moved them away, so....

File: test/Label.test.js (hunk 6 above)
Comment (wimrijnders) [reply test/Label.test.js]: ['Idem'](http://www.dictionary.com/browse/idem) : Same as previous comment in this column.

Comment (wimrijnders) [reply test/Label.test.js]: Overview:
- The priority of the options are:  `node, group, default node, global default`.
- `black` is in 'default node'.
- multi-font options, if defined, take precedence. The main font options are fall-backs for the multi-font options.

Specific:
- Node 0 has no 'node' or 'group' options, hence uses 'default node'.
- Nodes 1 has `group2`, which has a default font but no explicit bold font. The bold definition in 'default node' trumps this.
- Node 2 has `group1`, the same logic as with Node 1 applies here.
- Nodes 3 and 4 have bold fonts defined in the node instance. These trump everything.

Welcome to the wonderful world of multi-font options. Precisely this kind of thing is what made fixing the issue so hard. My head still hurts.

File: test/Label.test.js (hunk 7 above)
Comment (wimrijnders) [reply test/Label.test.js]: Yes, but `dataNodes` is not changed anywhere, so the same original values are being entered in the `DataSet` instance, and `DataSet` copies values internally.

Crap, let me confirm that.

File: test/Label.test.js (hunk 8 above)
Comment (wimrijnders) [reply test/Label.test.js]: I guess; they're kind of lengthy, that's true. I'll have a think about how to carve this up.

File: lib/network/modules/components/shared/Label.js [hunk 18]
```diff
@@ -2,11 +2,44 @@ let util = require('../../../../util');
...
+ *  - prototypes are totally ignored. The idea is to add option objects used as prototypes
+ *    to the pile, in the correct order.
+ */
+
+
+/**
+ * List of special styles for multi-fonts
+ * @private
+ */
+const multiFontStyle = ['bold', 'ital', 'boldital', 'mono'];
```
Comment (mbroad) [inline lib/network/modules/components/shared/Label.js]: `normal` is omitted?

File: test/Label.test.js (hunk 8 above)
Comment (mbroad) [reply test/Label.test.js]: Excellent! The only other suggestion I'll make is to follow the mocha convention for `pending`, or write the entire test and use `skip`, as described here: https://mochajs.org

This is a nit pick, and I'm approving as-is, with or without my suggestion.

**Comment by wimrijnders** [comment]
`pending` and `skip` conventions are new to me. I suppose the intention would be to get rid of the TODO's at the top of the unit test file(s)?

OK, I think this is a minor thing. I will leave it as is, but thanks for pointing it out.

**Comment by wimrijnders** [comment]
@justinharrel, since your comment on `widthConstraint` appears to have been deleted, I take it that the wrapping is not an issue? Just checking.

**Comment by justinharrell** [comment]
I accidentally commented on commit rather than PR, its still there. widthConstraint still does not seem to work.

Should I just make a new issue?

**Comment by wimrijnders** [comment]
What another failing case? Sure, make a new issue. If you can give a test-case that would be welcome.
