### PR TITLE
Fix subgroup collision

### LINKED ISSUE #3199: Non-colliding subgroups cause stacking
When subgroup 1 has an item with an end equal to a second subgroup 2 start time, The subgroups will stack even when `stackSubgroups: false`

### PR DESCRIPTION
**Pull request by yotamberk**
fixes #3199

### CODE REVIEW

File: lib/timeline/component/Group.js [hunk 1]
```diff
@@ -498,7 +496,7 @@ Group.prototype._updateSubgroupsSizes = function () {
       })
 
       me.subgroups[subgroup].start = newStart;
-      me.subgroups[subgroup].end = newEnd;
+      me.subgroups[subgroup].end = new Date(newEnd - 1) // -1 to compensate for colliding end to start subgroups;
```
Comment (wimrijnders) [inline lib/timeline/component/Group.js]: Why is the conversion to `Date` necessary here? Field `start` doesn't appear to need it, and the code works fine without it.

Also, the result is that it's possible to have the new end become `newEnd - 2`. I know this is nitpicking about milliseconds, but still....I present an alternative in the main review comment, see if that makes sense (I am a virgin with respect to `timeline`).

File: examples/timeline/items/expectedVsActualTimesItems.html [hunk 2]
```diff
@@ -85,13 +85,32 @@
...
+            group:'group1', 
+            subgroup:'sg_3'
+        },
+        {
+            id: 6, 
+            content: 'item 3 (actual time)', 
+            start: '2014-01-17T12:00:00',
+            end: '2014-01-18T12:00:00',
+            group:'group1', 
+            subgroup:'sg_3'
```
Comment (wimrijnders) [inline examples/timeline/items/expectedVsActualTimesItems.html]: 👍 for updating example.

File: lib/timeline/component/Group.js [hunk 3]
```diff
@@ -486,7 +484,7 @@ Group.prototype._updateSubgroupsSizes = function () {
   if (me.subgroups) {
     for (var subgroup in me.subgroups) {
       var newStart = me.subgroups[subgroup].items[0].data.start;
-      var newEnd = me.subgroups[subgroup].items[0].data.end;
+      var newEnd = me.subgroups[subgroup].items[0].data.end - 1;
 
       me.subgroups[subgroup].items.forEach(function(item) {
         if (new Date(item.data.start) < new Date(newStart)) {
```
Comment (wimrijnders) [inline lib/timeline/component/Group.js]: I understand this is not part of your change, but why is it necessary to convert to `Date` here? You can compare millisecond values directly. Is there perhaps a mixup of types for the start and end fields? That they can be either milliseconds or of type `Date`?

I hereby note that all comparisons between `Date` and milliseconds work, except the obvious:

```js
a = 1000000;
b = new Date(1000000);
a == b;    // false!
a === b;   // false!

// But following as expected
a < b;    // false
a <= b;   // true
a >= b;   // true
a > b;    // false
```

Which is just one more inconsistency in javascript. But it does mean that all `new Date()` parts can be removed in the conditions here. Just an observation.

Comment (yotamberk) [inline lib/timeline/component/Group.js]: I agree. But because we allow the user to add strings to the `start` and `end` of items, we might encounter comparisons of strings, which is very not good. So as a precaution and to keep consistency in the timeline, Dates are always used for comparisons. I think a better way would have been using `Moment` but This works too

File: lib/timeline/component/Group.js (hunk 1 above)
Comment (yotamberk) [inline lib/timeline/component/Group.js]: Yeah, it can be `newEnd-2` but this is a simple solution for the colliding subgroups. This is the simplest solution to avoid collision of subgroup items. These are by definition a wrapper for items and don't have a real meaning as items. That's why solving their limits by subtracting 1 ms is more correct than fixing the `isColliding` function in `stack.js` file in my opinion.

File: lib/timeline/component/Group.js (hunk 3 above)
Comment (wimrijnders) [inline lib/timeline/component/Group.js]: Ah right, string dates. I haven't thought that far. OK then the comparisons make sense. However, see new points.

File: lib/timeline/component/Group.js [hunk 4]
```diff
@@ -486,7 +484,7 @@ Group.prototype._updateSubgroupsSizes = function () {
   if (me.subgroups) {
     for (var subgroup in me.subgroups) {
       var newStart = me.subgroups[subgroup].items[0].data.start;
-      var newEnd = me.subgroups[subgroup].items[0].data.end;
+      var newEnd = me.subgroups[subgroup].items[0].data.end - 1;
```
Comment (wimrijnders) [inline lib/timeline/component/Group.js]: If `data.end` can be a string then `- 1` is not adequate.

File: lib/timeline/component/Group.js (hunk 1 above)
Comment (wimrijnders) [inline lib/timeline/component/Group.js]: If `newEnd` can be a string then `- 1` is not adequate.

File: lib/timeline/component/Group.js (hunk 3 above)
Comment (wimrijnders) [inline lib/timeline/component/Group.js]: Ah right, string dates. I haven't thought that far. OK then the comparisons make sense. However, see new points.

File: lib/timeline/component/Group.js (hunk 4 above)
Comment (yotamberk) [inline lib/timeline/component/Group.js]: I was wrong. It's already converted to a date...

File: lib/timeline/component/Group.js (hunk 1 above)
Comment (yotamberk) [inline lib/timeline/component/Group.js]: The reason I do want to leave the `new Date()` is for consistency. I don't want the `start` to be a Date and the `end` to be a Date in milliseconds.

**Comment by wimrijnders** [comment]
OK, so given that `start` and `end` are always `Date` instancess, I can see that the code will work and I can approve.

For reference, I will hereby record my criticism:

* There is no need to do the interim conversions to `Date` if the start and end fields are `Date` instances already.
* The correction on `end` can be more than 1 millisecond.

But these are not critical notes. The code will work regardless.

**Comment by yotamberk** [comment]
Thanks again @wimrijnders . Notes taken!
